/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   services_tcp.c                                     :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: arsciand <arsciand@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/01/09 15:06:59 by arsciand          #+#    #+#             */
/*   Updated: 2022/01/09 15:31:44 by arsciand         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_nmap.h"

const char  *services_tcp(uint16_t port)
{
    switch (port)
    {
        case 1:
            return "tcpmux";
        case 2:
            return "compressnet";
        case 4:
            return "unknown";
        case 5:
            return "rje";
        case 11:
            return "systat";
        case 13:
            return "daytime";
        case 15:
            return "netstat";
        case 17:
            return "qotd";
        case 18:
            return "msp";
        case 19:
            return "chargen";
        case 23:
            return "telnet";
        case 24:
            return "priv";
        case 25:
            return "smtp";
        case 26:
            return "rsftp";
        case 27:
            return "nsw";
        case 29:
            return "msg";
        case 31:
            return "msg";
        case 33:
            return "dsp";
        case 35:
            return "priv";
        case 37:
            return "time";
        case 38:
            return "rap";
        case 39:
            return "rlp";
        case 41:
            return "graphics";
        case 42:
            return "nameserver";
        case 43:
            return "whois";
        case 44:
            return "mpm";
        case 45:
            return "mpm";
        case 46:
            return "mpm";
        case 47:
            return "ni";
        case 48:
            return "auditd";
        case 49:
            return "tacacs";
        case 50:
            return "re";
        case 51:
            return "la";
        case 52:
            return "xns";
        case 53:
            return "domain";
        case 54:
            return "xns";
        case 55:
            return "isi";
        case 56:
            return "xns";
        case 57:
            return "priv";
        case 58:
            return "xns";
        case 59:
            return "priv";
        case 61:
            return "ni";
        case 62:
            return "acas";
        case 63:
            return "via";
        case 64:
            return "covia";
        case 65:
            return "tacacs";
        case 66:
            return "sqlnet";
        case 67:
            return "dhcps";
        case 68:
            return "dhcpc";
        case 69:
            return "tftp";
        case 70:
            return "gopher";
        case 71:
            return "netrjs";
        case 72:
            return "netrjs";
        case 73:
            return "netrjs";
        case 74:
            return "netrjs";
        case 75:
            return "priv";
        case 76:
            return "deos";
        case 77:
            return "priv";
        case 78:
            return "vettcp";
        case 79:
            return "finger";
        case 81:
            return "hosts2";
        case 82:
            return "xfer";
        case 83:
            return "mit";
        case 84:
            return "ctf";
        case 86:
            return "mfcobol";
        case 87:
            return "priv";
        case 88:
            return "kerberos";
        case 89:
            return "su";
        case 90:
            return "dnsix";
        case 91:
            return "mit";
        case 92:
            return "npp";
        case 93:
            return "dcp";
        case 94:
            return "objcall";
        case 95:
            return "supdup";
        case 96:
            return "dixie";
        case 97:
            return "swift";
        case 98:
            return "linuxconf";
        case 99:
            return "metagram";
        case 100:
            return "newacct";
        case 101:
            return "hostname";
        case 102:
            return "iso";
        case 103:
            return "gppitnp";
        case 104:
            return "acr";
        case 105:
            return "csnet";
        case 106:
            return "pop3pw";
        case 107:
            return "rtelnet";
        case 108:
            return "snagas";
        case 109:
            return "pop2";
        case 110:
            return "pop3";
        case 111:
            return "rpcbind";
        case 112:
            return "mcidas";
        case 113:
            return "ident";
        case 114:
            return "audionews";
        case 115:
            return "sftp";
        case 116:
            return "ansanotify";
        case 117:
            return "uucp";
        case 118:
            return "sqlserv";
        case 119:
            return "nntp";
        case 120:
            return "cfdptkt";
        case 121:
            return "erpc";
        case 122:
            return "smakynet";
        case 123:
            return "ntp";
        case 124:
            return "ansatrader";
        case 125:
            return "locus";
        case 126:
            return "unitary";
        case 127:
            return "locus";
        case 128:
            return "gss";
        case 129:
            return "pwdgen";
        case 130:
            return "cisco";
        case 131:
            return "cisco";
        case 132:
            return "cisco";
        case 133:
            return "statsrv";
        case 134:
            return "ingres";
        case 135:
            return "msrpc";
        case 136:
            return "profile";
        case 137:
            return "netbios";
        case 138:
            return "netbios";
        case 139:
            return "netbios";
        case 140:
            return "emfis";
        case 141:
            return "emfis";
        case 142:
            return "bl";
        case 143:
            return "imap";
        case 144:
            return "news";
        case 145:
            return "uaac";
        case 146:
            return "iso";
        case 147:
            return "iso";
        case 148:
            return "cronus";
        case 149:
            return "aed";
        case 150:
            return "sql";
        case 151:
            return "hems";
        case 152:
            return "bftp";
        case 153:
            return "sgmp";
        case 154:
            return "netsc";
        case 155:
            return "netsc";
        case 156:
            return "sqlsrv";
        case 157:
            return "knet";
        case 158:
            return "pcmail";
        case 159:
            return "nss";
        case 160:
            return "sgmp";
        case 161:
            return "snmp";
        case 162:
            return "snmptrap";
        case 163:
            return "cmip";
        case 164:
            return "cmip";
        case 165:
            return "xns";
        case 166:
            return "s";
        case 167:
            return "namp";
        case 168:
            return "rsvd";
        case 169:
            return "send";
        case 170:
            return "print";
        case 171:
            return "multiplex";
        case 172:
            return "cl";
        case 173:
            return "xyplex";
        case 174:
            return "mailq";
        case 175:
            return "vmnet";
        case 176:
            return "genrad";
        case 177:
            return "xdmcp";
        case 178:
            return "nextstep";
        case 180:
            return "ris";
        case 181:
            return "unify";
        case 182:
            return "audit";
        case 183:
            return "ocbinder";
        case 184:
            return "ocserver";
        case 185:
            return "remote";
        case 186:
            return "kis";
        case 187:
            return "aci";
        case 188:
            return "mumps";
        case 189:
            return "qft";
        case 190:
            return "gacp";
        case 191:
            return "prospero";
        case 192:
            return "osu";
        case 193:
            return "srmp";
        case 194:
            return "irc";
        case 195:
            return "dn6";
        case 196:
            return "dn6";
        case 197:
            return "dls";
        case 198:
            return "dls";
        case 199:
            return "smux";
        case 200:
            return "src";
        case 201:
            return "at";
        case 202:
            return "at";
        case 203:
            return "at";
        case 204:
            return "at";
        case 205:
            return "at";
        case 206:
            return "at";
        case 207:
            return "at";
        case 208:
            return "at";
        case 209:
            return "tam";
        case 210:
            return "z39";
        case 211:
            return "914c";
        case 212:
            return "anet";
        case 213:
            return "ipx";
        case 214:
            return "vmpwscs";
        case 215:
            return "softpc";
        case 216:
            return "atls";
        case 217:
            return "dbase";
        case 218:
            return "mpp";
        case 219:
            return "uarps";
        case 220:
            return "imap3";
        case 221:
            return "fln";
        case 222:
            return "rsh";
        case 223:
            return "cdc";
        case 224:
            return "masqdialer";
        case 242:
            return "direct";
        case 243:
            return "sur";
        case 244:
            return "dayna";
        case 245:
            return "link";
        case 246:
            return "dsp3270";
        case 247:
            return "subntbcst_tftp";
        case 248:
            return "bhfhs";
        case 256:
            return "fw1";
        case 257:
            return "fw1";
        case 258:
            return "fw1";
        case 259:
            return "esro";
        case 260:
            return "openport";
        case 261:
            return "nsiiops";
        case 262:
            return "arcisdms";
        case 263:
            return "hdap";
        case 264:
            return "bgmp";
        case 265:
            return "maybe";
        case 266:
            return "sst";
        case 267:
            return "td";
        case 268:
            return "td";
        case 269:
            return "manet";
        case 270:
            return "gist";
        case 271:
            return "pt";
        case 280:
            return "http";
        case 281:
            return "personal";
        case 282:
            return "cableport";
        case 283:
            return "rescap";
        case 284:
            return "corerjd";
        case 286:
            return "fxp";
        case 287:
            return "k";
        case 308:
            return "novastorbakcup";
        case 309:
            return "entrusttime";
        case 310:
            return "bhmds";
        case 311:
            return "asip";
        case 312:
            return "vslmp";
        case 313:
            return "magenta";
        case 314:
            return "opalis";
        case 315:
            return "dpsi";
        case 316:
            return "decauth";
        case 317:
            return "zannet";
        case 318:
            return "pkix";
        case 319:
            return "ptp";
        case 320:
            return "ptp";
        case 321:
            return "pip";
        case 322:
            return "rtsps";
        case 323:
            return "rpki";
        case 324:
            return "rpki";
        case 333:
            return "texar";
        case 344:
            return "pdap";
        case 345:
            return "pawserv";
        case 346:
            return "zserv";
        case 347:
            return "fatserv";
        case 348:
            return "csi";
        case 349:
            return "mftp";
        case 350:
            return "matip";
        case 351:
            return "matip";
        case 352:
            return "dtag";
        case 353:
            return "ndsauth";
        case 354:
            return "bh611";
        case 355:
            return "datex";
        case 356:
            return "cloanto";
        case 357:
            return "bhevent";
        case 358:
            return "shrinkwrap";
        case 359:
            return "tenebris_nts";
        case 360:
            return "scoi2odialog";
        case 361:
            return "semantix";
        case 362:
            return "srssend";
        case 363:
            return "rsvp_tunnel";
        case 364:
            return "aurora";
        case 365:
            return "dtk";
        case 366:
            return "odmr";
        case 367:
            return "mortgageware";
        case 368:
            return "qbikgdp";
        case 369:
            return "rpc2portmap";
        case 370:
            return "codaauth2";
        case 371:
            return "clearcase";
        case 372:
            return "ulistserv";
        case 373:
            return "legent";
        case 374:
            return "legent";
        case 375:
            return "hassle";
        case 376:
            return "nip";
        case 377:
            return "tnETOS";
        case 378:
            return "dsETOS";
        case 379:
            return "is99c";
        case 380:
            return "is99s";
        case 381:
            return "hp";
        case 382:
            return "hp";
        case 383:
            return "hp";
        case 384:
            return "arns";
        case 385:
            return "ibm";
        case 386:
            return "asa";
        case 387:
            return "aurp";
        case 388:
            return "unidata";
        case 389:
            return "ldap";
        case 390:
            return "uis";
        case 391:
            return "synotics";
        case 392:
            return "synotics";
        case 393:
            return "dis";
        case 394:
            return "embl";
        case 395:
            return "netcp";
        case 396:
            return "netware";
        case 397:
            return "mptn";
        case 398:
            return "kryptolan";
        case 399:
            return "iso";
        case 400:
            return "work";
        case 401:
            return "ups";
        case 402:
            return "genie";
        case 403:
            return "decap";
        case 404:
            return "nced";
        case 405:
            return "ncld";
        case 406:
            return "imsp";
        case 407:
            return "timbuktu";
        case 408:
            return "prm";
        case 409:
            return "prm";
        case 410:
            return "decladebug";
        case 411:
            return "rmt";
        case 412:
            return "synoptics";
        case 413:
            return "smsp";
        case 414:
            return "infoseek";
        case 415:
            return "bnet";
        case 416:
            return "silverplatter";
        case 417:
            return "onmux";
        case 418:
            return "hyper";
        case 419:
            return "ariel1";
        case 420:
            return "smpte";
        case 421:
            return "ariel2";
        case 422:
            return "ariel3";
        case 423:
            return "opc";
        case 424:
            return "opc";
        case 425:
            return "icad";
        case 426:
            return "smartsdp";
        case 427:
            return "svrloc";
        case 428:
            return "ocs_cmu";
        case 429:
            return "ocs_amu";
        case 430:
            return "utmpsd";
        case 431:
            return "utmpcd";
        case 432:
            return "iasd";
        case 433:
            return "nnsp";
        case 434:
            return "mobileip";
        case 435:
            return "mobilip";
        case 436:
            return "dna";
        case 437:
            return "comscm";
        case 438:
            return "dsfgw";
        case 439:
            return "dasp";
        case 440:
            return "sgcp";
        case 441:
            return "decvms";
        case 442:
            return "cvc_hostd";
        case 444:
            return "snpp";
        case 445:
            return "microsoft";
        case 446:
            return "ddm";
        case 447:
            return "ddm";
        case 448:
            return "ddm";
        case 449:
            return "as";
        case 450:
            return "tserver";
        case 451:
            return "sfs";
        case 452:
            return "sfs";
        case 453:
            return "creativeserver";
        case 454:
            return "contentserver";
        case 455:
            return "creativepartnr";
        case 456:
            return "macon";
        case 457:
            return "scohelp";
        case 458:
            return "appleqtc";
        case 459:
            return "ampr";
        case 460:
            return "skronk";
        case 461:
            return "datasurfsrv";
        case 462:
            return "datasurfsrvsec";
        case 463:
            return "alpes";
        case 464:
            return "kpasswd5";
        case 465:
            return "smtps";
        case 466:
            return "digital";
        case 467:
            return "mylex";
        case 468:
            return "photuris";
        case 469:
            return "rcp";
        case 470:
            return "scx";
        case 471:
            return "mondex";
        case 472:
            return "ljk";
        case 473:
            return "hybrid";
        case 474:
            return "tn";
        case 475:
            return "tcpnethaspsrv";
        case 476:
            return "tn";
        case 477:
            return "ss7ns";
        case 478:
            return "spsc";
        case 479:
            return "iafserver";
        case 480:
            return "loadsrv";
        case 481:
            return "dvs";
        case 482:
            return "bgs";
        case 483:
            return "ulpnet";
        case 484:
            return "integra";
        case 485:
            return "powerburst";
        case 486:
            return "sstats";
        case 487:
            return "saft";
        case 488:
            return "gss";
        case 489:
            return "nest";
        case 490:
            return "micom";
        case 491:
            return "go";
        case 492:
            return "ticf";
        case 493:
            return "ticf";
        case 494:
            return "pov";
        case 495:
            return "intecourier";
        case 496:
            return "pim";
        case 497:
            return "retrospect";
        case 498:
            return "siam";
        case 499:
            return "iso";
        case 500:
            return "isakmp";
        case 501:
            return "stmf";
        case 502:
            return "mbap";
        case 503:
            return "intrinsa";
        case 504:
            return "citadel";
        case 505:
            return "mailbox";
        case 506:
            return "ohimsrv";
        case 507:
            return "crs";
        case 508:
            return "xvttp";
        case 509:
            return "snare";
        case 510:
            return "fcp";
        case 511:
            return "passgo";
        case 512:
            return "exec";
        case 513:
            return "login";
        case 514:
            return "shell";
        case 515:
            return "printer";
        case 516:
            return "videotex";
        case 517:
            return "talk";
        case 518:
            return "ntalk";
        case 519:
            return "utime";
        case 520:
            return "efs";
        case 521:
            return "ripng";
        case 522:
            return "ulp";
        case 523:
            return "ibm";
        case 524:
            return "ncp";
        case 525:
            return "timed";
        case 526:
            return "tempo";
        case 527:
            return "stx";
        case 528:
            return "custix";
        case 530:
            return "courier";
        case 531:
            return "conference";
        case 532:
            return "netnews";
        case 533:
            return "netwall";
        case 534:
            return "mm";
        case 535:
            return "iiop";
        case 536:
            return "opalis";
        case 537:
            return "nmsp";
        case 538:
            return "gdomap";
        case 539:
            return "apertus";
        case 540:
            return "uucp";
        case 541:
            return "uucp";
        case 542:
            return "commerce";
        case 543:
            return "klogin";
        case 544:
            return "kshell";
        case 545:
            return "ekshell";
        case 546:
            return "dhcpv6";
        case 547:
            return "dhcpv6";
        case 548:
            return "afp";
        case 549:
            return "idfp";
        case 550:
            return "new";
        case 551:
            return "cybercash";
        case 552:
            return "deviceshare";
        case 553:
            return "pirp";
        case 554:
            return "rtsp";
        case 555:
            return "dsf";
        case 556:
            return "remotefs";
        case 557:
            return "openvms";
        case 558:
            return "sdnskmp";
        case 559:
            return "teedtap";
        case 560:
            return "rmonitor";
        case 561:
            return "monitor";
        case 562:
            return "chshell";
        case 563:
            return "snews";
        case 564:
            return "9pfs";
        case 565:
            return "whoami";
        case 566:
            return "streettalk";
        case 567:
            return "banyan";
        case 568:
            return "ms";
        case 569:
            return "ms";
        case 570:
            return "meter";
        case 571:
            return "umeter";
        case 572:
            return "sonar";
        case 573:
            return "banyan";
        case 574:
            return "ftp";
        case 575:
            return "vemmi";
        case 576:
            return "ipcd";
        case 577:
            return "vnas";
        case 578:
            return "ipdd";
        case 579:
            return "decbsrv";
        case 580:
            return "sntp";
        case 581:
            return "bdp";
        case 582:
            return "scc";
        case 583:
            return "philips";
        case 584:
            return "keyserver";
        case 585:
            return "imap4";
        case 586:
            return "password";
        case 587:
            return "submission";
        case 588:
            return "cal";
        case 589:
            return "eyelink";
        case 590:
            return "tns";
        case 591:
            return "http";
        case 592:
            return "eudora";
        case 593:
            return "http";
        case 594:
            return "tpip";
        case 595:
            return "cab";
        case 596:
            return "smsd";
        case 597:
            return "ptcnameservice";
        case 598:
            return "sco";
        case 599:
            return "acp";
        case 600:
            return "ipcserver";
        case 601:
            return "syslog";
        case 602:
            return "xmlrpc";
        case 603:
            return "mnotes";
        case 604:
            return "tunnel";
        case 605:
            return "soap";
        case 606:
            return "urm";
        case 607:
            return "nqs";
        case 608:
            return "sift";
        case 609:
            return "npmp";
        case 610:
            return "npmp";
        case 611:
            return "npmp";
        case 612:
            return "hmmp";
        case 613:
            return "hmmp";
        case 614:
            return "sshell";
        case 615:
            return "sco";
        case 616:
            return "sco";
        case 617:
            return "sco";
        case 618:
            return "dei";
        case 619:
            return "compaq";
        case 620:
            return "sco";
        case 621:
            return "escp";
        case 622:
            return "collaborator";
        case 623:
            return "oob";
        case 624:
            return "cryptoadmin";
        case 625:
            return "apple";
        case 626:
            return "apple";
        case 627:
            return "passgo";
        case 628:
            return "qmqp";
        case 629:
            return "3com";
        case 630:
            return "rda";
        case 631:
            return "ipp";
        case 632:
            return "bmpp";
        case 633:
            return "servstat";
        case 634:
            return "ginad";
        case 635:
            return "rlzdbase";
        case 636:
            return "ldapssl";
        case 637:
            return "lanserver";
        case 638:
            return "mcns";
        case 639:
            return "msdp";
        case 640:
            return "entrust";
        case 641:
            return "repcmd";
        case 642:
            return "esro";
        case 643:
            return "sanity";
        case 644:
            return "dwr";
        case 645:
            return "pssc";
        case 646:
            return "ldp";
        case 647:
            return "dhcp";
        case 648:
            return "rrp";
        case 649:
            return "cadview";
        case 650:
            return "obex";
        case 651:
            return "ieee";
        case 652:
            return "hello";
        case 653:
            return "repscmd";
        case 654:
            return "aodv";
        case 655:
            return "tinc";
        case 656:
            return "spmp";
        case 657:
            return "rmc";
        case 658:
            return "tenfold";
        case 660:
            return "mac";
        case 661:
            return "hap";
        case 662:
            return "pftp";
        case 663:
            return "purenoise";
        case 664:
            return "secure";
        case 665:
            return "sun";
        case 666:
            return "doom";
        case 667:
            return "disclose";
        case 668:
            return "mecomm";
        case 669:
            return "meregister";
        case 670:
            return "vacdsm";
        case 671:
            return "vacdsm";
        case 672:
            return "vpps";
        case 673:
            return "cimplex";
        case 674:
            return "acap";
        case 675:
            return "dctp";
        case 676:
            return "vpps";
        case 677:
            return "vpp";
        case 678:
            return "ggf";
        case 679:
            return "mrm";
        case 680:
            return "entrust";
        case 681:
            return "entrust";
        case 682:
            return "xfr";
        case 683:
            return "corba";
        case 684:
            return "corba";
        case 685:
            return "mdc";
        case 686:
            return "hcp";
        case 687:
            return "asipregistry";
        case 688:
            return "realm";
        case 689:
            return "nmap";
        case 690:
            return "vatp";
        case 691:
            return "resvc";
        case 692:
            return "hyperwave";
        case 693:
            return "connendp";
        case 694:
            return "ha";
        case 695:
            return "ieee";
        case 696:
            return "rushd";
        case 697:
            return "uuidgen";
        case 698:
            return "olsr";
        case 699:
            return "accessnetwork";
        case 700:
            return "epp";
        case 701:
            return "lmp";
        case 702:
            return "iris";
        case 704:
            return "elcsd";
        case 705:
            return "agentx";
        case 706:
            return "silc";
        case 707:
            return "borland";
        case 709:
            return "entrustmanager";
        case 710:
            return "entrust";
        case 711:
            return "cisco";
        case 712:
            return "tbrpf";
        case 713:
            return "iris";
        case 714:
            return "iris";
        case 715:
            return "iris";
        case 716:
            return "pana";
        case 723:
            return "omfs";
        case 729:
            return "netviewdm1";
        case 730:
            return "netviewdm2";
        case 731:
            return "netviewdm3";
        case 741:
            return "netgw";
        case 742:
            return "netrcs";
        case 744:
            return "flexlm";
        case 747:
            return "fujitsu";
        case 748:
            return "ris";
        case 749:
            return "kerberos";
        case 750:
            return "kerberos";
        case 751:
            return "kerberos_master";
        case 752:
            return "qrh";
        case 753:
            return "rrh";
        case 754:
            return "krb_prop";
        case 758:
            return "nlogin";
        case 759:
            return "con";
        case 760:
            return "krbupdate";
        case 761:
            return "kpasswd";
        case 762:
            return "quotad";
        case 763:
            return "cycleserv";
        case 764:
            return "omserv";
        case 765:
            return "webster";
        case 767:
            return "phonebook";
        case 769:
            return "vid";
        case 770:
            return "cadlock";
        case 771:
            return "rtip";
        case 772:
            return "cycleserv2";
        case 773:
            return "submit";
        case 774:
            return "rpasswd";
        case 775:
            return "entomb";
        case 776:
            return "wpages";
        case 777:
            return "multiling";
        case 780:
            return "wpgs";
        case 783:
            return "spamassassin";
        case 786:
            return "concert";
        case 787:
            return "qsc";
        case 799:
            return "controlit";
        case 800:
            return "mdbs_daemon";
        case 801:
            return "device";
        case 802:
            return "mbap";
        case 808:
            return "ccproxy";
        case 810:
            return "fcp";
        case 828:
            return "itm";
        case 829:
            return "pkix";
        case 830:
            return "netconf";
        case 831:
            return "netconf";
        case 832:
            return "netconfsoaphttp";
        case 833:
            return "netconfsoapbeep";
        case 847:
            return "dhcp";
        case 848:
            return "gdoi";
        case 853:
            return "domain";
        case 854:
            return "dlep";
        case 860:
            return "iscsi";
        case 861:
            return "owamp";
        case 862:
            return "twamp";
        case 871:
            return "supfilesrv";
        case 873:
            return "rsync";
        case 886:
            return "iclcnet";
        case 887:
            return "iclcnet_svinfo";
        case 888:
            return "accessbuilder";
        case 898:
            return "sun";
        case 900:
            return "omginitialrefs";
        case 901:
            return "samba";
        case 902:
            return "iss";
        case 903:
            return "iss";
        case 910:
            return "kink";
        case 911:
            return "xact";
        case 912:
            return "apex";
        case 913:
            return "apex";
        case 950:
            return "oftep";
        case 953:
            return "rndc";
        case 975:
            return "securenetpro";
        case 989:
            return "ftps";
        case 990:
            return "ftps";
        case 991:
            return "nas";
        case 992:
            return "telnets";
        case 993:
            return "imaps";
        case 994:
            return "ircs";
        case 995:
            return "pop3s";
        case 996:
            return "xtreelic";
        case 997:
            return "maitrd";
        case 998:
            return "busboy";
        case 999:
            return "garcon";
        case 1001:
            return "webpush";
        case 1002:
            return "windows";
        case 1008:
            return "ufsd";
        case 1010:
            return "surf";
        case 1021:
            return "exp1";
        case 1022:
            return "exp2";
        case 1023:
            return "netvenuechat";
        default:
            return NULL;
    }
}
