/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   services_udp.c                                     :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: arsciand <arsciand@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/01/09 15:07:33 by arsciand          #+#    #+#             */
/*   Updated: 2022/01/12 19:06:11 by cempassi         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_nmap.h"

const char  *services_udp(uint16_t port)
{
    switch (port)
    {
        case 1:
            return "tcpmux";
        case 2:
            return "compressnet";
        case 4:
            return "unknown";
        case 5:
            return "rje";
        case 11:
            return "systat";
        case 13:
            return "daytime";
        case 15:
            return "netstat";
        case 17:
            return "qotd";
        case 18:
            return "msp";
        case 19:
            return "chargen";
        case 20:
            return "ftp-data";
        case 21:
            return "ftp";
        case 22:
            return "ssh";
        case 23:
            return "telnet";
        case 24:
            return "priv";
        case 25:
            return "smtp";
        case 26:
            return "rsftp";
        case 27:
            return "nsw";
        case 29:
            return "msg-icp";
        case 31:
            return "msg-auth";
        case 33:
            return "dsp";
        case 35:
            return "priv";
        case 37:
            return "time";
        case 38:
            return "rap";
        case 39:
            return "rlp";
        case 41:
            return "graphics";
        case 42:
            return "nameserver";
        case 43:
            return "whois";
        case 44:
            return "mpm";
        case 45:
            return "mpm";
        case 46:
            return "mpm";
        case 47:
            return "ni";
        case 48:
            return "auditd";
        case 49:
            return "tacacs";
        case 50:
            return "re-mail-ck";
        case 51:
            return "la";
        case 52:
            return "xns";
        case 53:
            return "domain";
        case 54:
            return "xns";
        case 55:
            return "isi";
        case 56:
            return "xns";
        case 57:
            return "priv";
        case 58:
            return "xns";
        case 59:
            return "priv";
        case 61:
            return "ni";
        case 62:
            return "acas";
        case 63:
            return "via";
        case 64:
            return "covia";
        case 65:
            return "tacacs";
        case 66:
            return "sqlnet";
        case 67:
            return "dhcps";
        case 68:
            return "dhcpc";
        case 69:
            return "tftp";
        case 70:
            return "gopher";
        case 71:
            return "netrjs";
        case 72:
            return "netrjs";
        case 73:
            return "netrjs";
        case 74:
            return "netrjs";
        case 75:
            return "priv";
        case 76:
            return "deos";
        case 77:
            return "priv";
        case 78:
            return "vettcp";
        case 79:
            return "finger";
        case 81:
            return "hosts2";
        case 82:
            return "xfer";
        case 83:
            return "mit";
        case 84:
            return "ctf";
        case 86:
            return "mfcobol";
        case 87:
            return "priv";
        case 88:
            return "kerberos";
        case 89:
            return "su";
        case 90:
            return "dnsix";
        case 91:
            return "mit";
        case 92:
            return "npp";
        case 93:
            return "dcp";
        case 94:
            return "objcall";
        case 95:
            return "supdup";
        case 96:
            return "dixie";
        case 97:
            return "swift";
        case 98:
            return "tacnews";
        case 106:
            return "3com-tsmux";
        case 113:
            return "auth";
        case 164:
            return "smip-agent";
        case 190:
            return "cacp";
        case 257:
            return "set";
        case 258:
            return "yak-chat";
        case 259:
            return "firewall1-rdp";
        case 264:
            return "fw1-or-bgmp";
        case 265:
            return "x-bone-ctl";
        case 474:
            return "tn-tl-w2";
        case 480:
            return "iafdbase";
        case 481:
            return "ph";
        case 482:
            return "xlog";
        case 486:
            return "avian";
        case 512:
            return "biff";
        case 513:
            return "who";
        case 514:
            return "syslog";
        case 520:
            return "route";
        case 545:
            return "appleqtcsrvr";
        case 603:
            return "idxp";
        case 623:
            return "asf-rmcp";
        case 625:
            return "dec_dlm";
        case 626:
            return "serialnumberd";
        case 635:
            return "mount";
        case 636:
            return "ldaps";
        case 640:
            return "pcnfs";
        case 650:
            return "bwnfs";
        case 691:
            return "msexch-routing";
        case 737:
            return "sometimes-rpc2";
        case 754:
            return "tell";
        case 760:
            return "ns";
        case 761:
            return "rxe";
        case 773:
            return "notify";
        case 774:
            return "acmaint_dbd";
        case 775:
            return "acmaint_transd";
        case 810:
            return "fcp-udp";
        case 901:
            return "smpnameres";
        case 902:
            return "ideafarm-door";
        case 903:
            return "ideafarm-panic";
        case 996:
            return "vsinet";
        case 998:
            return "puparp";
        case 999:
            return "applix";
        case 1000:
            return "ock";
        case 1012:
            return "sometimes-rpc1";
        default:
            return "unasigned";
    }
}
