name: C CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make DEBUG=hard
    - name: env
      run: pip3 install -r requirements.txt
    - name: test
      run: make test
